######################################################################
# Automatically generated by qmake (2.01a) Thu May 17 20:59:07 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += wwidget.h
SOURCES += main.cpp wwidget.cpp
