######################################################################
# Automatically generated by qmake (2.01a) Fri May 18 08:06:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += wwidget.h
SOURCES += main.cpp wwidget.cpp
